name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: black-hulling-359518
  SERVICE_NAME: ticket-scout
  REGION: us-west1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # This step authenticates the GitHub Action runner to Google Cloud
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/95093689493/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          service_account: 'github-deployer-sa@black-hulling-359518.iam.gserviceaccount.com'

      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          source: .
          secrets: |
            FIREBASE_API_KEY=FIREBASE_API_KEY:latest
            FIREBASE_MESSAGING_SENDER_ID=FIREBASE_MESSAGING_SENDER_ID:latest
            FIREBASE_APP_ID=FIREBASE_APP_ID:latest
            GMAIL_USER=GMAIL_USER:latest
            GMAIL_APP_PASSWORD=GMAIL_APP_PASSWORD:latest
            TICKETMASTER_API_KEY=TICKETMASTER_API_KEY:latest
          env_vars: |
            TM_AUTH_COOKIE=${{ secrets.TM_AUTH_COOKIE }}
            TM_QUEUE_TOKEN=${{ secrets.TM_QUEUE_TOKEN }}
